### PR TITLE
Adds /api/v1/json/filters endpoints

### PR DESCRIPTION
**Pull request by SomewhatDamaged**
### Before you begin

* I understand my contributions may be rejected for any reason
* I understand my contributions are for the benefit of Derpibooru and/or the Philomena software
* I understand my contributions are licensed under the GNU AGPLv3

- [x] I understand all of the above

---

This adds a `/api/v1/json/filters` endpoint that will return `system` filters or `system` filters and `user` filters if an API key is given. Will also paginate through `user` filters using a `page` parameter.

### CODE REVIEW

**Comment by liamwhite** [comment]
I wonder if system and user filters shouldn't be split out into separate endpoints.

**Comment by SomewhatDamaged** [comment]
Maybe break them out into `/api/v1/json/filters/system` and `/api/v1/json/filters/user`?

**Comment by liamwhite** [comment]
Sounds good to me

**Comment by SomewhatDamaged** [comment]
There. Now the two endpoints are:
`/api/v1/json/filters/system`
`/api/v1/json/filters/user`
Preserving:
`/api/v1/json/filters/:id`

**Comment by SomewhatDamaged** [comment]
Also removed an errant preload.

**Pull request merged**
