### PR TITLE
Add Bluesky scraper

### PR DESCRIPTION
**Pull request by Yay295**
### Before you begin

* I understand my contributions may be rejected for any reason
* I understand my contributions are for the benefit of Derpibooru and/or the Philomena software
* I understand my contributions are licensed under the GNU AGPLv3

- [X] I understand all of the above

---

Added a scraper for Bluesky.

### CODE REVIEW

**Review by mdashlw — CHANGES_REQUESTED** [review]
should use `com.atproto.sync.getBlob` instead of fullsize url to get the original image file

**Comment by Yay295** [comment]
I got it to load once, but it hasn't loaded again for some reason.

Original Post: https://bsky.app/profile/cutepencilcase.bsky.social/post/3l67wiia73t2i
Post API Data: https://public.api.bsky.app/xrpc/app.bsky.feed.getPosts?uris=at://did:plc:jcwrxnab2rhxdr5ru3q6vscv/app.bsky.feed.post/3l67wiia73t2i
Fullsize Image: https://cdn.bsky.app/img/feed_fullsize/plain/did:plc:jcwrxnab2rhxdr5ru3q6vscv/bafkreiguvtp4vbz24yzapfqutkpgq5vbydpvoaewzmcvrw6gz2diwuk2rq@jpeg
Blob?: https://bsky.app/xrpc/com.atproto.sync.getBlob?did=did:plc:jcwrxnab2rhxdr5ru3q6vscv&cid=bafkreiguvtp4vbz24yzapfqutkpgq5vbydpvoaewzmcvrw6gz2diwuk2rq

**Comment by Yay295** [comment]
looks like it's https://bsky.social/xrpc/com.atproto.sync.getBlob?did=did:plc:jcwrxnab2rhxdr5ru3q6vscv&cid=bafkreiguvtp4vbz24yzapfqutkpgq5vbydpvoaewzmcvrw6gz2diwuk2rq

**Comment by liamwhite** [comment]
Moved upstream to https://github.com/philomena-dev/philomena/commit/a08510f21efa7ec3a32082f70d4420b64b73c156

**Pull request merged**
